app = "surf-journal"
primary_region = "sjc"

[env]
  DATABASE_URL = "sqlite3:///mnt/volume/production.sqlite3"
  RAILS_ENV = "production"

[mounts]
  source = "sqlite3_volume"
  destination = "/mnt/volume"

[build]
  image = "registry.fly.io/surf-journal:latest"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250