schema = 3

[mod]
  [mod."github.com/go-chi/chi"]
    version = "v1.5.5"
    hash = "sha256-sLWNbqjlOXEMN1QxYDrU88CRfT7Qnp3EMqs87Sl5gu8="
  [mod."github.com/go-chi/chi/v5"]
    version = "v5.2.1"
    hash = "sha256-oOi39n1MMETVl9ZKCODhlmFe0f/znEgxI3nJOW8yy2o="
  [mod."github.com/gorilla/securecookie"]
    version = "v1.1.2"
    hash = "sha256-KeMHNM9emxX+N0WYiZsTii7n8sNsmjWwbnQ9SaJfTKE="
  [mod."github.com/gorilla/sessions"]
    version = "v1.4.0"
    hash = "sha256-cLK2z1uOEz7Wah/LclF65ptYMqzuvaRnfIGYqtn3b7g="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.24"
    hash = "sha256-taGKFZFQlR5++5b2oZ1dYS3RERKv6yh1gniNWhb4egg="
  [mod."golang.org/x/crypto"]
    version = "v0.36.0"
    hash = "sha256-Np+suvZdMOXALDm4m8nDNa+QsvUV0rE0PEINuxCoKGM="
  [mod."golang.org/x/sys"]
    version = "v0.31.0"
    hash = "sha256-aulv5obCrhheMlSq7seUgP3C29nfZABwiQ4IBNisgME="
  [mod."golang.org/x/term"]
    version = "v0.30.0"
    hash = "sha256-bgN4cMED7P2SqFZQZPNRPJL2Px35chNoWaqNhLDEoZM="
