# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
# Only trigger, when the CI workflow succeeded
on:
  workflow_run:
    workflows: ["CI"]
    branches:
      - 'main'
    types:
      - completed

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: nicknovitski/nix-develop@v1
      - name: Run `nix build`
        run: nix build .#container
      - run: ./bin/publish
        env:
          FLY_AUTH_TOKEN: ${{ secrets.FLY_API_TOKEN }}
